### ISSUE TITLE
Scripts for ENHSP

### ISSUE THREAD

**Issue by gabrielplicks** [AI-Planning/planutils#13]
Hello Christian! Following-up our discussion on the other repository, I tried creating the scripts for an ENHSP package based on your `TEMPLATE` scripts. I am not sure if the commands I am executing respect the working directory in which you will be executing the script from (please review that if you can). Also, I am not sure how you will set the variables for setting the domain and problem in the `run` script. Here they go:

**install.sh** (notice that I need `sudo` for installing packages and changing permissions)
```
#!/bin/bash

# To use if root is required
[ "$UID" -eq 0 ] || (echo "installation requires root access"; exec sudo "$0" "$@")

# Install general linux dependencies
sudo apt install openjdk-8-jre openjdk-8-jdk

# General setup / configuration
wget https://gitlab.com/enricos83/ENHSP-Public/-/archive/master/ENHSP-Public-master.zip
unzip ENHSP-Public-master.zip
rm ENHSP-Public-master.zip
mv ENHSP-Public-master/ enhsp
cd enhsp
./compile
./install
sudo chmod +x enhsp
```

**run.sh** (you can set the heuristic using the flag `-h`)
```
#!/bin/bash

./enhsp --domain $1 --problem $2
```

**uninstall.sh**
```
#!/bin/bash

rm -rf enhsp/
```

**manifest.json**
```
{
    "name": "ENHSP",
    "description": "Expressive Numeric Heuristic Search Planner (https://gitlab.com/enricos83/ENHSP-Public)",
    "dependencies": []
}
```

**Comment by Maumagnaguagno** [comment]
Note that there is a warning in the README of ENHSP and many versions are available, more information [here](https://sites.google.com/view/enhsp/). The new ENHSP-20 does not link to an available source yet. Some users may prefer a specific version based on the website description:
> What to choose? If you are after non-linear problems with processes, I would go with ENHSP-20. Otherwise ENHSP-19. Only if nothing works, go to ENHSP-18

**Comment by haz** [comment]
This likely means that there should be multiple recipes. E.g., `ehsp` and `ehsp19` or whatever. Will reach out to Enrico to see what he'd suggest.

**Comment by enricos83** [comment]
Hola! Thanks for taking care of this!
So:
1. Yes I think it is better to have multiple recipes (I hope this will end soon when I am done transporting all functionalities in enhsp20). In particular enhsp18 enhsp19 enhsp20. I know this isn't great and it can be confusing, but there are really major changes and haven't the resources to really test the whole retro-compatibility myself alone. From the repository (https://gitlab.com/enricos83/ENHSP-Public/) enhsp18 is on master branch, enhsp19 is on enhsp-19 and enhsp20 in enhsp-20 :)
2. ENHSP, much like FastDownward, is more like a framework in that it has several search engines/ heuristics/configurations. Differently from FD though, there isn't a proper planner name (e.g., LAMA) for a given combo. I have tried to achieve so using the -planner option (see https://sites.google.com/view/enhsp/home/how-to-use-it?authuser=0), but I think that for the moment it is just better to let the script accept unbounded parameters with the "$@" (or maybe you have already thought that). Otherwise we could have specific recipes for these planners? Open to suggestions

Thanks again guys

Enrico

**Comment by haz** [comment]
1. Perfect. But I think it's still useful to have a default. So 4 command-line options will be available: `enhsp18`, `enhsp19`, `enhsp20`, and `enhsp`. The main question for you, is what do you want the last one (`enhsp`) to point to? We'll just redirect it to one of the other 3.

2. Unbound certainly makes the most sense to me. If you think there's a common one that warrants its own single command-line (like `lama` doing for `downward`), then we can add it later.

**Comment by enricos83** [comment]
1. enhsp19. Question. Can we then change it? Like can I do it in the future?
2. All good then!

**Comment by haz** [comment]
1. Absolutely! It'll just be a simple change to the `enhsp` run script and dependencies.
2. 👍 
3. @gabrielplicks Can you take a stab at these 4 recipes with the latest version of the template (things changed slightly). Also, it's always better if you can just do it with binaries instead of building: https://sites.google.com/view/enhsp/
4. @enricos83 Looks like you only have binaries for `enhsp19` and `enhsp20`. Any chance you can build/host one for `enhsp18` as well?

**Comment by enricos83** [comment]
1, 2, 3, . Great
4. I'd like to, but I don't have space to host it long-term. The links you find on the webpage are google drive files, which are tricky to wrapper and download automatically (there maybe some workaround but this may not work for long term). That is why I put enhsp-20 code as well in a branch in gitlab. Maybe I can host some binary on gitlab/github as well? Do you know how this can be done in a clean way?

**Comment by Maumagnaguagno** [comment]
You can link binaries in [GitLab releases](https://docs.gitlab.com/ee/user/project/releases/) and include binaries in [Github releases](https://help.github.com/en/github/administering-a-repository/managing-releases-in-a-repository).

**Comment by haz** [comment]
Aye, if it's on GitHub/GitLab, then releases are definitely the way to go!

**Comment by haz** [comment]
@enricos83 Can you let us know when you have the binaries located somewhere convenient? Smaller the payload, the better ;). Once you post here, I'll confirm if they work inside of the planutils docker. If not, we may want to try and embed them in a singularity image like the other planners are doing.

@gabrielplicks If you wanted to start a PR on this, that'd be great. GitHub keeps track of who contributed through PR's, and it's easier that way for us to list everyone who's helped out (as opposed to me copying what you write in issue discussions and then taking all of the credit!)

**Comment by gabrielplicks** [comment]
@haz Sure, I will start a PR this weekend hopefully :) I could not work on this lately cause I've been quite busy.

**Comment by enricos83** [comment]
Yes, I am looking into gitlab releases. Will let you know ASAP.

**Comment by enricos83** [comment]
I have made the three releases on Gitlab, one for each enhsp following your suggestion. 
@Maumagnaguagno what do you mean by linking binary in github releases? you mean like having  other repositories in github that host the binaries?

**Comment by haz** [comment]
My read of @Maumagnaguagno 's suggestion was an "or" rather than an "and". GitLab releases should do, as long as we have the ability to `curl` or `wget` the binary.

**Comment by Maumagnaguagno** [comment]
Yes, that was an "or".
I was not sure which one you would choose based on your question.

The [ENSHP releases](https://gitlab.com/enricos83/ENHSP-Public/-/releases) include source code assets, but differently from the links in https://sites.google.com/view/enhsp/ I see no way of getting a compressed folder with a compiled enshp*.jar .
Not sure if there is a hidden page within GitLab with the binaries ready to download, which I think is what @haz wants to avoid installing multiple dependencies.

**Comment by enricos83** [comment]
No, I haven't put any binary because I have no way of hosting it. I understood your message as "you can use binary releases to do that" but I have likely misinterpreted what you were saying (realized that after trying hard this way with no success). So...you are basically suggesting that I could provide a link, maybe the one on the website? The problem with that link though, is that it is a google drive file which is a bit cumbersome to wrap... Sorry guys this thing remains a bit obscure to me :D . Would releasing the source code be such a problem? You only need to run compile (of course you need a compatible java compiler); this generates a jar file that can be executed by just typing java -jar enhsp.jar. Let me know!

**Comment by haz** [comment]
Well there's a few things tied up here:

1. We need to decide if java is worth considering as a native dependency -vs- wrapping enhsp in a singularity image.
2. If you host the .jar or .sif (singularity image) somewhere, we'd want to be able to get at it with just a command-line tool (so no google drive interface to find the download). With .sif, this is easily done with singularity hub, but with .jar, we'd need a place to put it. I thought that gitlab offered such things. Seems like this may indeed be the case: https://docs.gitlab.com/ee/user/project/releases/#permanent-links-to-release-assets

@FlorianPommerening Thoughts on Q1, given your experience with running the IPC through singularity?

**Comment by enricos83** [comment]
@haz Regarding point 2 I am not sure that is the case. Or say, I don't fully understand what they are proposing. Maybe the way is to upload a file following this https://docs.gitlab.com/ee/api/projects.html#upload-a-file . I will need to have a closer look at it.

**Comment by enricos83** [comment]
For the record: I tried to make gitlab yield artifacts, like binaries, directly into releases. It seems that one can do so by linking the result of the CI pipeline which should be provided as an evidence. (https://docs.gitlab.com/ee/user/project/releases/#include-report-artifacts-as-release-evidence-ultimate-only.) However, for some reasons, I have not succeeded, run out of time (spent like 2 hours on this). If there is someone who has managed to do this, please let me know. This may be the solution of our problem.

**Comment by gabrielplicks** [comment]
@haz I created a PR with the scripts I made for downloading/compiling/installing ENHSP. I know they will have to be modified later to get the hosted binaries. Anyway, I didn't find a way to link the PR to this issue (maybe I'm not allowed).

**Comment by FlorianPommerening** [comment]
My suggestion would be to wrap the planner and the Java VM in a Singularity container. I don't have much experience with this but as far as I'm aware Java can be tricky with running older source code on newer VMs or the other way around, so if you get want to include a different planner that expects a different VM version, this might cause problems and require two different JVMs to be installed.

As for the hosting question, as long as the source code is available, it shouldn't be a problem to compile it inside the singularity image. There are two alternatives for that: 
A) hosting the compiled singularity image, for example through singularity hub
B) hosting the singularity recipe file and letting planutils build the image

Option A would be preferable because the installation would be faster and would not require root privileges. But at least for singularity hub it would mean you'd need a github repository that contains the recipe file (as far as I'm aware they don't support gitlab but that may have changed). Option B would be lower effort to set up. You could even have the recipe file live inside the planutils package directory so all required changes would be here. Of course if you want to make the recipe file accessible to other users (without planutils), it might make more sense to host it somewhere else (e.g., together with the source code).

**Comment by enricos83** [comment]
As far as I know, backward compatibility issues in JAVA are practical non-existent. But if you have some example (also only one :)) when this has happened, well we have to do as you suggest. Actually this may be the safest solution anyway.

Now, say we go Option A. Do we need to transfer the whole repo in github, or just have the recipe file(s) there (just to be sure)?

**Comment by FlorianPommerening** [comment]
It is sufficient to just host the recipe files there if the recipe knows where to get the source code from. This is also what we do for Fast Downward: you can find the container files at https://github.com/aibasel/downward but it might not be the best example, because we generate both docker and singularity containers, so our singularity recipe is just "import the docker container".

**Comment by gabrielplicks** [comment]
@FlorianPommerening @enricos83 Regarding JAVA backward compatibility, I`ve previously had problems trying to compile ENHSP using newer versions of openjdk (version 11 as far as I remember). I am sure openjdk-8 works for compiling ENHSP.

**Comment by haz** [comment]
There's also the option to host the singularity recipe in `planutils` or another `ai-planning` repository dedicated to planner compilation recipes. Just wouldn't be shipped with the pip package, and assumed that the builds would be hosted on singularity hub. That shifts "ownership" to some extent to the `ai-planning` org. Even if just perceptual, it may not be something you (@enricos83 ) or other planner authors want.

Given the above discussion, I think singularity is the way to go as well here.

**Comment by enricos83** [comment]
@haz I think I'll follow Fast downward way. Make a recipe on github for the various planners.
@gabrielplicks  Well that is a great spot. Never saw that until now you tell me. This may have to do with my configurations obscuring for some strange reasons that problem. More precisely, there is a weird urinet something exception for compiling enhsp-18 with versions above openjdk-8. 

I am organizing the whole machinery right now.
@haz What locations are you referring to?

**Comment by enricos83** [comment]
*Small update* I have added the recipes for singularity images in a new repository: https://github.com/enricos83/enhsp-containers
This took me a (big) while. I hope this is what we were expecting. 
I have tested the resulting images, and after some tweaking the recipes produce a file of ~150MB. I don't see how this can be made smaller considering that I have to wrap the JVM together with a whole OS.
The next step would be to link these recipes to singularity images (as far as I understood). Right?
@haz can you tell me if this is what you were expecting?

**Comment by FlorianPommerening** [comment]
I wrote something on how to get a small image a while ago, but it looks like you are already doing most of it: https://github.com/AI-Planning/planutils/wiki/Building-Singularity-Images#keeping-the-image-files-small

It's possible that the JRE is so large that it takes the bulk of the size. You can find out if that is the case by running a shell in the container (`singularity shell enhsp.sif`, I think) and using `du -ht 10M /` or something like this.

If you want to use Singularity hub, I think the recipes have to be called `Singularity.<tag>`, so in your case, for example, `Singularity.2018`, `Singularity.2019`, `Singularity.2020`. Singularity hub will create a container that is called `enricos83/enhsp-containers`. The name of the container is the name of the repository, so you might want to rename it to `enhsp`.  The container will then have with three tags:
`shub://enricos83/enhsp-containers:2018`, `shub://enricos83/enhsp-containers:2019`, and `shub://enricos83/enhsp-containers:2020`. You can also add a tag `latest` (or a file `Singularity` without a tag name). The tag `latest` is what people get if they just pull `shub://enricos83/enhsp-containers`.

**Comment by enricos83** [comment]
Thanks @FlorianPommerening ! I was not aware of the wiki.
I think the only way to minimize the size of the image further would be to strip away some unnecessary JRE functionality.  Anyway, this can be done later.

Now, to get my images searchable on Singularity hub, what should I do exactly?

**Comment by FlorianPommerening** [comment]
I have not done this step myself yet, so I cannot give good advice there. I think you have to log in at singularity hub with your github account to link the account. After that it should only require a little configuration to say which containers should be built and based on what triggers. There is a step-by-step guide here: https://singularityhub.github.io/singularityhub-docs/docs/getting-started/

**Comment by haz** [comment]
Just wanted to pipe up and say carry on ;).

This is all what I suspected we might end up doing. 150Mb doesn't seem so crazy given that we need the JVM in there anyways. I never knew about the singularity tagging -- this'll make it quite clean on the `planutils` front.

**Comment by enricos83** [comment]
The images are up and running, and ready to be downloaded on singularity hub. Just look for enhsp collection (https://singularity-hub.org/search) and then you will find the way to get your hands on the three versions, enhsp:2018, enhsp:2019, enhsp:2020. 

From now on, the idea is to use planutils to wrap (one more time again) the planner with another recipe file. Right? I may have some idea of more useful configurations, and therefore recipes.

**Comment by haz** [comment]
Awesome!

@gabrielplicks : want to update the PR to just do singularity pulls? There should be 4 packages, each corresponding to the command-line use (3 for each year, and one that is just `enhsp` and depends on (/redirects to) the 2019 one). The [lama](https://github.com/AI-Planning/planutils/tree/master/planutils/packages/downward) example is a good one to mirror.

**Comment by haz** [comment]
I know it's bad FOSS practice, but I just want to wrap this issue up quick: I've accepted the ENHSP PR, and will quickly revise things to the suggestion above. This way, we at least get @gabrielplicks on the contributor list ;). @enricos83 , we'll need to get you to update something later so you're there too!

Such a hack, I know...

**Comment by haz** [comment]
Ok, we're all set: https://github.com/AI-Planning/planutils/pull/26

Thanks all!

**Comment by gabrielplicks** [comment]
Thanks @haz! Great work! Sorry I was not active, I'm running behind schedule with my dissertation.

**Comment by haz** [comment]
A valid excuse for sure...happy writing!
