### ISSUE TITLE
Avoid flooding the PATH

### ISSUE THREAD

**Issue by haz** [AI-Planning/planutils#58]
Instead of adding to the `~/.bashrc` for getting the path updated, do the following:

- [x] Have a `planutils run {package}` functionality (closed with #49 )
- [x] Have a `planutils activate` that places adds the generic bin folder to the `PATH` variable.

**Comment by haz** [comment]
@jendrikseipp This largely comes from the discussion we had.

**Key question**: If we install a planner via planutils, should it appear on the PATH if not in the planutils activated environment? I.e., should this work:

```bash
$ planutils install lama
$ lama
```

...or should it only work like one of the following:

```bash
$ planutils install lama
$ planutils activate
$ lama
```

```bash
$ planutils install lama
$ planutils run lama
```

Certainly, you won't be able to just run `lama` if it's uninstalled, unless you are in the `planutils activate` mode.

**Comment by jendrikseipp** [comment]
I think all 3 versions are fine. In any case, I think when changing the PATH variable it's important to append the planutils dir, not to prepend it. Otherwise, I'll try to call my next planner ls or mkdir ;-) (see here for an interesting discussion about extending PATH: https://github.com/flatpak/flatpak/issues/994)

The first version is like apt-get, pip and pipx. Actually, the code that pipx uses for its "ensurepath" command could be useful for planutils as well (for appending to PATH). The second version works like a Python virtual environment. And the third works like flatpak. So all of them are used in the wild. 

I think the more important question is "can we trust running these commands?" (applies to all three versions). But solving this problem adequately requires a lot of work, obviously. But then again, we have these nice container technologies and they could come in handy here for executing planners in a sandbox.

**Comment by jendrikseipp** [comment]
The only version I find counterintuitive is to allow calling `lama` without having installed it first. This should simply be an error, I think.

**Comment by jendrikseipp** [comment]
One more thought: I think versions 1 and 3 (which are implemented now) should cater for most users. Personally, I don't think that adding another version is worth the maintenance effort, especially since it's the most cumbersome one to use, in my opinion.

Regarding sandboxing: maybe we could add a "solve" command, allow calling "planutils solve lama mydomain.pddl mytask.pddl", and invoke the Singularity image in a way that only gives it access to these two files and a temporary directory for storing temporary files and the plan. I think SIngularity bind paths could come in handy here, but I don't know much about them: https://sylabs.io/guides/3.8/user-guide/bind_paths_and_mounts.html I think sandboxed execution would be a killer feature.

**Comment by haz** [comment]
Was meant to just be two options ;). I personally have a desire to have some option for exposing all existing executables (and installing where necessary). The new PR addresses this through the `planutils activate`

Option one above doesn't work, though. Would mean having an empty bin on path (and relying on bashrc) which is populated as planners are installed.

**Comment by haz** [comment]
PR is at https://github.com/AI-Planning/planutils/pull/60

**Comment by jendrikseipp** [comment]
The code is fine, but for my taste creating environments is overkill and a bit too magical, especially for new users. Personally, I'll stick to "planutils run" which I find the least intrusive and magical :-)

**Comment by haz** [comment]
Hehe, well the entire thing is full magical when you install planutils now. This at least hides it in an environment.
