### ISSUE TITLE
Question/enhancement request: ability to run planning in one bash command (without entering the activate mode)

### ISSUE THREAD

**Issue by jan-dolejsi** [AI-Planning/planutils#96]
I am trying to see how we could use planners installed by planutils from within VS Code (besides the planning-as-a-service, which will eventually also solve it). Today, the instructions say make two calls:

```bash
planutils activate
lama domain.pddl problem.pddl
```

The activation feels natural for the hands on phase, just after planutils installation, when the environment needs to be setup by a series of command-line calls. But beyond that to be able to interact with the planners from scripts (or from VS Code in this case), could we have a single line syntax such as this?

```bash
planutils some-switch lama domain.pddl problem.pddl
```

**Comment by haz** [comment]
Use `run` for `some-switch` and you should be all set.

**Comment by haz** [comment]
@jan-dolejsi Did the above work for you? Ok to close this issue?

**Comment by jan-dolejsi** [comment]
Yes. It works. I finally made time to setup my computer for planutils - plainly using Python, not Docker.

`pip install planutils`

`planutils activate`

when trying to run `lama domain.pddl problem.pddl` planutils offers to download lama, as it should, but failed to find `singularity`. I installed singularity using `sudo apt install singularity` as ubuntu suggested. But that was a grave mistake. I found the correct binary here https://github.com/sylabs/singularity/releases and then it worked!

Now my dilemma is whether I should wrap the `planutils run` in VS Code with the logic that is planner-specific e.g. the file where it outputs the plan. Or rather wrap the planner-as-a-service, which already wraps all supported planners with the necessary configuration and logic.

But we should also update the documentation for this use case i.e. Python+Singularity. And also the note about the `run` command.

**Comment by haz** [comment]
Wonderful! And since it's been opened, everything's changed ;). Well not everything...

Singularity is no more, replaced by [Apptainer](https://apptainer.org/), and it's far more trivial to install. So the prevailing wisdom of having Docker be the go-to for planutils will very soon become less relevant. Native installation will be "the way" for most.

As for your question on interfacing, I'd probably suggest going the server route. Not the full-on PaaS project, but the server wrapper that ships with planutils. Eventual plan (excuse the pun!) is to unify interfacing with planners through the PaaS API.

**Comment by jan-dolejsi** [comment]
Ah, no note about that on the Singularity github page, but it explains why some of the hyperlinks to guides/documentation are broken. I will therefore wait for `planutils` to migrate to Apptainer. This is now safely closed.
